CREATE TABLE Exercise(
  id SERIAL NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  CONSTRAINT Exercise_PK PRIMARY KEY(id)
);

INSERT INTO Exercise VALUES(1, 'Push-up', 'A bodyweight exercise that targets the chest, shoulders, and triceps. Start in a plank position with your hands shoulder-width apart, lower your body by bending your elbows, then push back up to the starting position.', 'Strength');
INSERT INTO Exercise VALUES(2, 'Squat', 'A lower body exercise that primarily targets the quadriceps, hamstrings, and glutes. Stand with feet shoulder-width apart, lower your body as if sitting in a chair, keeping your chest up and knees behind your toes, then return to the standing position.', 'Strength');
INSERT INTO Exercise VALUES(3, 'Lunge', 'A lower body exercise that targets the quadriceps, hamstrings, and glutes. Step forward with one leg, lowering your hips until both knees are bent at 90 degrees, then push off the front foot to return to the starting position.', 'Strength');
INSERT INTO Exercise VALUES(4, 'Burpees', 'A full-body exercise that combines a squat, jump, and push-up. Start standing, squat down, kick your feet back into a plank position, perform a push-up, jump your feet back towards your hands, and then jump up explosively.', 'Cardio');
INSERT INTO Exercise VALUES(5, 'Child Pose', 'A restorative yoga pose that stretches the back, hips, and arms. Start on your hands and knees, then sit your hips back toward your heels and extend your arms forward, resting your forehead on the ground.', 'Cardio');
INSERT INTO Exercise VALUES(6, 'Kettlebell Swing', 'A full-body exercise that targets the hips, glutes, and core. Stand with your feet shoulder-width apart, hold a kettlebell with both hands, swing it between your legs, then thrust your hips forward to swing it up to chest height.', 'Strength');
INSERT INTO Exercise VALUES(7, 'Plank', 'A core exercise that targets the abs, lower back, and shoulders. Start in a forearm plank position, keeping your body in a straight line from head to heels, and hold for a set amount of time.', 'Strength');
INSERT INTO Exercise VALUES(8, 'Bicep Curl', 'An isolation exercise that targets the biceps. Stand with dumbbells in each hand, palms facing forward, curl the weights towards your shoulders while keeping your elbows close to your body, then lower them back down.', 'Strength');
INSERT INTO Exercise VALUES(9, 'Overhead Shoulder Press', 'An upper body exercise that targets the shoulders and triceps. Stand or sit with a dumbbell or barbell in each hand at shoulder height, then press the weights overhead until your arms are fully extended.', 'Strength');
INSERT INTO Exercise VALUES(10, 'Deadlift', 'A compound movement that works the lower back, glutes, hamstrings, and core. Stand with feet shoulder-width apart, bend at the hips and knees to grab a barbell, then stand up straight, lifting the barbell while keeping your back flat.', 'Strength');
INSERT INTO Exercise VALUES(11, 'Jumping Jacks', 'A full-body exercise that increases heart rate and improves cardiovascular endurance. Start standing with your feet together and hands at your sides, then jump your feet out to the sides while raising your arms above your head. Jump back to the starting position.', 'Cardio');
INSERT INTO Exercise VALUES(12, 'High Knees', 'A cardio exercise that targets the lower body while boosting heart rate. Run in place, lifting your knees as high as possible toward your chest, while keeping your arms pumping at your sides.', 'Cardio');
INSERT INTO Exercise VALUES(13, 'Box Jumps', 'A plyometric exercise that builds strength and power while improving cardiovascular fitness. Stand in front of a box or platform, squat down, then jump onto the box with both feet, landing softly. Step down and repeat.', 'Cardio');
INSERT INTO Exercise VALUES(14, 'Jump Rope', ' A simple and effective cardio exercise that improves endurance and coordination. Use a jump rope to continuously jump over the rope as it swings around your body.', 'Cardio');
INSERT INTO Exercise VALUES(15, 'Running (Treadmill or Outdoor)', 'A classic cardio exercise that boosts cardiovascular health and endurance. Run at a steady pace, either on a treadmill or outdoors, focusing on maintaining a consistent pace.', 'Cardio');
INSERT INTO Exercise VALUES(16, 'Cycling (Stationary or Outdoor)', 'A low-impact cardio exercise that targets the legs while improving cardiovascular fitness. Cycle on a stationary bike or outdoors at varying intensities.', 'Cardio');
INSERT INTO Exercise VALUES(17, 'Hamstring Stretch', 'A flexibility exercise that targets the hamstrings. Sit on the floor with one leg extended and the other bent, then lean forward to touch your toes on the extended leg, keeping your back straight.', 'Cardio');
INSERT INTO Exercise VALUES(18, 'Quadriceps Stretch', 'A flexibility exercise for the front of the thighs. Stand on one leg, grab your ankle with the same-side hand, and gently pull your heel toward your glutes while keeping your knees close together.', 'Flexibility');
INSERT INTO Exercise VALUES(19, 'Hip Flexor Stretch', 'A stretch targeting the hip flexors. Step one foot forward into a lunge position, keeping your back leg straight and your hips pushing forward to stretch the hip flexor of the back leg.', 'Flexibility');
INSERT INTO Exercise VALUES(20, 'Cobra Stretch', 'A stretch for the chest, abs, and lower back. Lie face down on the floor, place your hands under your shoulders, and press your chest upward while keeping your lower body grounded.', 'Flexibility');
INSERT INTO Exercise VALUES(21, 'Butterfly Stretch', 'A flexibility exercise that targets the inner thighs and hips. Sit with your feet together and your knees bent out to the sides, then gently press your knees toward the ground.', 'Flexibility');
INSERT INTO Exercise VALUES(22, 'Triceps Stretch', 'A stretch that targets the triceps and shoulders. Reach one arm overhead and bend your elbow to touch the opposite shoulder blade, then use the opposite hand to gently press the elbow for a deeper stretch.', 'Flexibility');